Release/1.0.0 (#179)
* update NuGet dependencies

* Added SonarLint support to projects

* Bump Microsoft.NET.Test.Sdk from 16.7.0 to 16.7.1 in /src

Bumps [Microsoft.NET.Test.Sdk](https://github.com/microsoft/vstest) from 16.7.0 to 16.7.1.
- [Release notes](https://github.com/microsoft/vstest/releases)
- [Commits](https://github.com/microsoft/vstest/compare/v16.7.0...v16.7.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.Extensions.Configuration.EnvironmentVariables in /src

Bumps [Microsoft.Extensions.Configuration.EnvironmentVariables](https://github.com/aspnet/Extensions) from 3.1.0 to 3.1.7.
- [Release notes](https://github.com/aspnet/Extensions/releases)
- [Commits](https://github.com/aspnet/Extensions/compare/v3.1.0...v3.1.7)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.AspNetCore.DataProtection from 3.1.6 to 3.1.7 in /src

Bumps [Microsoft.AspNetCore.DataProtection](https://github.com/aspnet/AspNetCore) from 3.1.6 to 3.1.7.
- [Release notes](https://github.com/aspnet/AspNetCore/releases)
- [Commits](https://github.com/aspnet/AspNetCore/compare/v3.1.6...v3.1.7)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.CodeAnalysis.Scripting from 3.4.0 to 3.7.0 in /src

Bumps [Microsoft.CodeAnalysis.Scripting](https://github.com/dotnet/roslyn) from 3.4.0 to 3.7.0.
- [Release notes](https://github.com/dotnet/roslyn/releases)
- [Changelog](https://github.com/dotnet/roslyn/blob/master/docs/Breaking%20API%20Changes.md)
- [Commits](https://github.com/dotnet/roslyn/commits)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.Extensions.Configuration from 3.1.0 to 3.1.7 in /src

Bumps [Microsoft.Extensions.Configuration](https://github.com/aspnet/Extensions) from 3.1.0 to 3.1.7.
- [Release notes](https://github.com/aspnet/Extensions/releases)
- [Commits](https://github.com/aspnet/Extensions/compare/v3.1.0...v3.1.7)

Signed-off-by: dependabot[bot] <support@github.com>

* resolve Sonar Code Smells in ruleng

* resolve Code Smells in shared projects

* resolves MSB3277 on System.Text.Json

* resolves "Could not evaluate 'Microsoft.CSharp.dll' for extension metadata" warning

* resolve remaining Code Smells in ruleeng

* resolve Code Smells in host prj

* resolve Code Smells in function project

* resolve Code Smells in CLI project

* more Code Smells resolution

* resolve remaining code analysis warnings

* resolve code analysis warnings in tests

* Fix incorrect HTTP Header in web hook Subscriptions made by `map.local.rule`

* add GHCR in addition to DockerHub

* default 0.0.1-localdev version plus

attempt to prevent Script compilation failed run.csx(14,23): error CS1705

* Revert "resolves "Could not evaluate 'Microsoft.CSharp.dll' for extension metadata" warning"

This reverts commit 28e1bbc90a9e6ad3bd9085b22f0440707e8f1846.

* Fix CS1705 on run.csx

run.csx(14,23): error CS1705: Assembly 'aggregator-function' with identity 'aggregator-function, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Logging.Abstractions' with identity 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

* Revert "Revert "resolves "Could not evaluate 'Microsoft.CSharp.dll' for extension metadata" warning""

This reverts commit db80d9a9e9ff32c4ec69ed519cf1445470d2e373.

* event directive

* fix marketplace workflow

* clean old Directory.Build.targets

* Bump Microsoft.Extensions.DependencyInjection in /src

Bumps [Microsoft.Extensions.DependencyInjection](https://github.com/aspnet/Extensions) from 3.1.7 to 3.1.8.
- [Release notes](https://github.com/aspnet/Extensions/releases)
- [Commits](https://github.com/aspnet/Extensions/compare/v3.1.7...v3.1.8)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.Extensions.Configuration.EnvironmentVariables in /src

Bumps [Microsoft.Extensions.Configuration.EnvironmentVariables](https://github.com/aspnet/Extensions) from 3.1.0 to 3.1.8.
- [Release notes](https://github.com/aspnet/Extensions/releases)
- [Commits](https://github.com/aspnet/Extensions/compare/v3.1.0...v3.1.8)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.Extensions.Hosting from 3.1.7 to 3.1.8 in /src

Bumps [Microsoft.Extensions.Hosting](https://github.com/aspnet/Extensions) from 3.1.7 to 3.1.8.
- [Release notes](https://github.com/aspnet/Extensions/releases)
- [Commits](https://github.com/aspnet/Extensions/compare/v3.1.7...v3.1.8)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump Microsoft.Extensions.Configuration from 3.1.0 to 3.1.8 in /src

Bumps [Microsoft.Extensions.Configuration](https://github.com/aspnet/Extensions) from 3.1.0 to 3.1.8.
- [Release notes](https://github.com/aspnet/Extensions/releases)
- [Commits](https://github.com/aspnet/Extensions/compare/v3.1.0...v3.1.8)

Signed-off-by: dependabot[bot] <support@github.com>

* rollback Microsoft.NET.Sdk.Functions to a working version

* bump Function SDK

* fix DockerHub credential

* try limit marketplace workflow

* rename CI script

* avoid dependency on csproj path script

* sample build scripts

* rule out Function SDK from updates

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>